import {config} from './config.js';
const SESSION_KEY='coinplan-session';
let session=null,refreshing=null;
export const configured=()=>!!(config.supabaseUrl&&config.supabaseKey);
export const getSession=()=>session;
function readSession(){const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw);if(!value?.access_token||!value.refresh_token||!value.user?.id||!Number.isFinite(value.expires_at))throw Error('Invalid saved sign-in.');return value;}
function persist(value){const next={...value,expires_at:Date.now()+value.expires_in*1000};try{localStorage.setItem(SESSION_KEY,JSON.stringify(next));}catch{throw Error('This browser could not remember your sign-in. Check that website storage is allowed.');}session=next;sessionStorage.removeItem(SESSION_KEY);return session;}
export async function request(path,{method='GET',body,token=session?.access_token}={}){if(!configured())throw Error('Cloud connection has not been configured yet.');const r=await fetch(config.supabaseUrl+path,{method,headers:{apikey:config.supabaseKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const data=await r.json().catch(()=>({}));if(!r.ok){const error=Error(data.msg||data.message||data.error_description||data.error||'Cloud request failed.');error.status=r.status;throw error;}return data;}
export async function signIn(email,password){return persist(await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password},token:null}));}
export async function restore(){try{if(!localStorage.getItem(SESSION_KEY)){const legacy=sessionStorage.getItem(SESSION_KEY);if(legacy)localStorage.setItem(SESSION_KEY,legacy);}session=readSession();if(session)sessionStorage.removeItem(SESSION_KEY);}catch{session=null;return null;}if(session){try{await refresh();}catch{/* Keep the saved household available offline. Only rejected refresh credentials clear it. */}}return session;}
async function renew(){session=readSession();if(!session)throw Error('Sign in first.');if(Date.now()<session.expires_at-60000)return;const active=session;try{const next=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:active.refresh_token},token:null});const current=readSession();if(current?.refresh_token===active.refresh_token)persist(next);else session=current;}catch(error){const current=readSession();if(current?.refresh_token!==active.refresh_token){session=current;if(session)return;}else if([400,401,403].includes(error.status)){signOut();}throw error;}if(!session)throw Error('Sign in first.');}
export async function refresh(){if(!refreshing){refreshing=(globalThis.navigator?.locks?globalThis.navigator.locks.request('coinplan-auth-refresh',renew):renew()).finally(()=>{refreshing=null;});}return refreshing;}
export function signOut(){session=null;localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY);}
export async function loadCloud(){await refresh();return request('/rest/v1/coinplan_state?select=payload,revision');}
export async function saveCloud(payload,revision){await refresh();return request('/rest/v1/rpc/coinplan_save_state',{method:'POST',body:{p_payload:payload,p_revision:revision}});}
export async function bank(action,body={}){await refresh();return request('/functions/v1/'+config.bankFunction,{method:'POST',body:{action,...body}});}
