export const categories = [
 ['housing','Housing','fixed'],['utilities','Utilities','fixed'],['subscriptions','Subscriptions','fixed'],['insurance','Insurance','fixed'],['groceries','Groceries','flex'],['dining','Dining out','flex'],['transport','Transport','flex'],['shopping','Shopping','flex'],['entertainment','Entertainment','flex'],['health','Health','nonmonthly'],['pet','Pets','flex'],['travel','Travel','nonmonthly'],['other','Other','flex'],['income','Income','income'],['transfer','Transfer / card payment','transfer']
].map(([id,name,bucket])=>({id,name,bucket}));
export const owners=['Shared','Brody','Mackenzie'];
export const isoToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function money(cents){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);}
export function cents(input){const s=String(input).trim().replace(/[$,]/g,'');if(!/^-?\d+(\.\d{1,2})?$/.test(s))throw Error('Enter an amount with at most two decimal places.');const n=Math.round(Number(s)*100);if(!Number.isSafeInteger(n)||Math.abs(n)>1e12)throw Error('Amount is too large.');return n;}
export function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return !isNaN(d)&&d.toISOString().slice(0,10)===s;}
export const id=()=>crypto.randomUUID();
export function emptyState(){return {version:2,revision:0,accounts:[],transactions:[],bills:[],goals:[],rules:[],budgets:{},settings:{mode:'category'}};}
export function validate(s){if(s?.version!==2||!Number.isSafeInteger(s.revision)||s.revision<0)throw Error('Invalid backup version.');for(const key of ['accounts','transactions','bills','goals','rules']){if(!Array.isArray(s[key]))throw Error('Invalid '+key);const ids=new Set();for(const r of s[key]){if(!r||typeof r.id!=='string'||ids.has(r.id))throw Error('Duplicate or invalid records.');ids.add(r.id);}}if(!s.budgets||typeof s.budgets!=='object'||Array.isArray(s.budgets)||!s.settings)throw Error('Invalid budget settings.');for(const t of s.transactions){if(typeof t.merchant!=='string'||!categories.some(c=>c.id===t.category)||!owners.includes(t.owner)||!Number.isSafeInteger(t.amount)||!validDate(t.date)||!['expense','income','transfer'].includes(t.type))throw Error('Invalid transaction.');}for(const a of s.accounts){if(typeof a.name!=='string'||!owners.includes(a.owner)||!Number.isSafeInteger(a.balance)||!['asset','liability'].includes(a.kind))throw Error('Invalid account.');}for(const b of s.bills){if(typeof b.name!=='string'||!owners.includes(b.owner)||!Number.isSafeInteger(b.amount)||b.amount<0||!validDate(b.anchor)||!['monthly','weekly','biweekly','yearly'].includes(b.frequency))throw Error('Invalid bill.');}for(const g of s.goals){if(typeof g.name!=='string'||!owners.includes(g.owner)||!Number.isSafeInteger(g.target)||g.target<=0||!Number.isSafeInteger(g.saved)||g.saved<0)throw Error('Invalid goal.');}for(const r of s.rules)if(typeof r.match!=='string'||!r.match.trim()||!categories.some(c=>c.id===r.category))throw Error('Invalid category rule.');for(const budget of Object.values(s.budgets)){if(!budget||typeof budget!=='object'||Array.isArray(budget))throw Error('Invalid budget.');for(const n of Object.values(budget))if(!Number.isSafeInteger(n)||n<0)throw Error('Invalid budget amount.');}return s;}
export function monthSummary(s,month,owner='All'){const tx=s.transactions.filter(t=>t.date.startsWith(month)&&!t.pending&&!t.hidden&&(owner==='All'||t.owner===owner));const income=tx.filter(t=>t.type==='income').reduce((n,t)=>n+t.amount,0);const spent=tx.filter(t=>t.type==='expense').reduce((n,t)=>n+t.amount,0);const byCategory={};for(const t of tx.filter(t=>t.type==='expense'))byCategory[t.category]=(byCategory[t.category]||0)+t.amount;return {income,spent,net:income-spent,byCategory,transactions:tx};}
export function netWorth(s){const assets=s.accounts.filter(a=>a.kind==='asset'&&!a.archived).reduce((n,a)=>n+a.balance,0);const liabilities=s.accounts.filter(a=>a.kind==='liability'&&!a.archived).reduce((n,a)=>n+a.balance,0);return {assets,liabilities,total:assets-liabilities};}
export function occurrences(b,month){if(b.archived)return [];const [year,mm]=month.split('-').map(Number);const start=Date.UTC(year,mm-1,1),end=Date.UTC(year,mm,1);const anchor=Date.parse(b.anchor+'T00:00:00Z');const dates=[];if(b.frequency==='monthly'||b.frequency==='yearly'){if(b.frequency==='yearly'&&Number(b.anchor.slice(5,7))!==mm)return dates;const day=Math.min(Number(b.anchor.slice(8,10)),new Date(end-86400000).getUTCDate());const value=Date.UTC(year,mm-1,day);if(value>=anchor)dates.push(new Date(value).toISOString().slice(0,10));}else{const step=(b.frequency==='weekly'?7:14)*86400000;for(let value=anchor+Math.max(0,Math.ceil((start-anchor)/step))*step;value<end;value+=step)dates.push(new Date(value).toISOString().slice(0,10));}return dates;}
export function budgetFor(s,month){const previous=Object.keys(s.budgets).filter(k=>k<=month).sort().at(-1);return previous?s.budgets[previous]:{};}
export function applyRules(t,rules){const r=rules.find(r=>t.merchant.toLowerCase().includes(r.match.toLowerCase()));return r?{...t,category:r.category,type:r.category==='income'?'income':r.category==='transfer'?'transfer':t.type}:t;}
export function parseCSV(text){text=text.replace(/^\uFEFF/,'');if(text.length>10_000_000)throw Error('CSV must be under 10 MB.');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||cell==='')quoted=!quoted;else throw Error('Unexpected quote in CSV.');}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Unclosed quote in CSV.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)throw Error('CSV needs a header and at least one transaction.');return {headers:rows[0],rows:rows.slice(1)};}
export function importDate(s){s=s.trim();if(validDate(s))return s;const m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m){const d=`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;if(validDate(d))return d;}throw Error('Use YYYY-MM-DD or MM/DD/YYYY dates.');}
export function mapCSV(parsed,map,accountId,owner,rules=[]){const counts=new Map();return parsed.rows.map((r,i)=>{try{const date=importDate(r[map.date]||'');const merchant=(r[map.merchant]||'').trim();if(!merchant)throw Error('Missing description');let raw=cents(r[map.amount]||'');if(map.expensePositive)raw=-raw;const category=(r[map.category]||'').trim().toLowerCase();const type=category==='transfer'?'transfer':category==='income'?'income':categories.some(c=>c.id===category&&c.bucket!=='transfer'&&c.bucket!=='income')?'expense':raw<0?'expense':'income';const base=JSON.stringify([accountId,date,merchant,raw]);const occurrence=(counts.get(base)||0)+1;counts.set(base,occurrence);return applyRules({id:id(),accountId,owner,date,merchant,amount:type==='expense'?-raw:raw,type,category:categories.some(c=>c.id===category)?category:type==='income'?'income':type==='transfer'?'transfer':'other',note:'',pending:false,source:'csv',importKey:base+'#'+occurrence},rules);}catch(e){throw Error(`Row ${i+2}: ${e.message}`);}});}
export function mergeImports(s,records){const seen=new Set(s.transactions.map(t=>t.importKey).filter(Boolean));const added=records.filter(t=>!seen.has(t.importKey));return {state:{...s,transactions:[...s.transactions,...added]},added:added.length,duplicates:records.length-added.length};}
export function migrateLegacy(tx,income,bills){const s=emptyState();const account={id:id(),name:'Previous CoinPlan entries',kind:'asset',balance:0,owner:'Brody',source:'manual'};s.accounts.push(account);const cats={gas:'transport',bills:'housing'};s.transactions=[...tx.map(t=>({...t,id:'legacy-'+t.id,amount:cents(t.amount),type:'expense',category:cats[t.category]||t.category,accountId:account.id,owner:'Brody',source:'legacy',pending:false})),...income.map(t=>({id:'legacy-'+t.id,amount:cents(t.amount),merchant:t.note||'Income',date:t.date,type:'income',category:'income',accountId:account.id,owner:'Brody',source:'legacy',pending:false}))];s.bills=bills.map(b=>({...b,id:'legacy-'+b.id,amount:cents(b.amount),anchor:`${isoToday().slice(0,7)}-${String(Math.min(b.dueDay||1,28)).padStart(2,'0')}`,archived:!b.active,owner:'Brody'}));return validate(s);}
export function mergeBank(s,bank){const prior=new Map(s.transactions.filter(t=>t.source==='plaid').map(t=>[t.id,t]));const incoming=new Set(bank.accounts.map(a=>a.id));const localTx=s.transactions.filter(t=>t.source!=='plaid');const referenced=new Set(localTx.map(t=>t.accountId));const oldAccounts=new Map(s.accounts.map(a=>[a.id,a]));const accounts=new Map(s.accounts.filter(a=>a.source!=='plaid'||incoming.has(a.id)||referenced.has(a.id)).map(a=>[a.id,a.source==='plaid'&&!incoming.has(a.id)?{...a,archived:true,hidden:true}:a]));for(const a of bank.accounts)accounts.set(a.id,{...a,owner:oldAccounts.get(a.id)?.owner||'Shared'});const tx=bank.transactions.map(t=>{const p=prior.get(t.id)||prior.get(t.pendingId);return applyRules({...t,owner:p?.owner||accounts.get(t.accountId)?.owner||'Shared',category:p?.customCategory||t.category,type:p?.customType||t.type,note:p?.note||'',reviewed:p?.reviewed||false,customCategory:p?.customCategory,customType:p?.customType},p?.customCategory?[]:s.rules);});return validate({...s,accounts:[...accounts.values()],transactions:[...s.transactions.filter(t=>t.source!=='plaid'),...tx]});}
