import test from 'node:test';
import assert from 'node:assert/strict';
const key='coinplan-session';let instance=0;
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k),clear:()=>values.clear()};};
const saved=(expires_at=Date.now()+3600000)=>({access_token:'fake-access',refresh_token:'fake-refresh',expires_at,expires_in:3600,user:{id:'fake-household'}});
const next=()=>({...saved(),access_token:'fake-renewed-access',refresh_token:'fake-renewed-refresh'});
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const module=()=>import('../js/cloud.js?test='+ ++instance);
function setup(){globalThis.localStorage=storage();globalThis.sessionStorage=storage();Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});globalThis.fetch=async()=>{throw Error('Unexpected network request');};}
test('sign-in survives app restart without saving a password',async()=>{setup();globalThis.fetch=async()=>response(saved());const first=await module();await first.signIn('fake@example.com','fake-password');assert.equal(JSON.stringify(localStorage.getItem(key)).includes('fake-password'),false);sessionStorage.clear();const reopened=await module();assert.equal((await reopened.restore()).user.id,'fake-household');assert.equal(reopened.getSession().access_token,'fake-access');});
test('an existing session migrates from temporary to persistent storage',async()=>{setup();sessionStorage.setItem(key,JSON.stringify(saved()));const auth=await module();assert.equal((await auth.restore()).user.id,'fake-household');assert.ok(localStorage.getItem(key));assert.equal(sessionStorage.getItem(key),null);});
test('expired sign-in refreshes once for concurrent bank and cloud requests',async()=>{setup();localStorage.setItem(key,JSON.stringify(saved(Date.now()-1000)));let refreshes=0;globalThis.fetch=async(url,options)=>{if(url.includes('refresh_token')){refreshes++;return response(next());}assert.equal(options.headers.Authorization,'Bearer fake-renewed-access');return response([]);};const auth=await module();await Promise.all([auth.restore(),auth.loadCloud(),auth.bank('connections')]);assert.equal(refreshes,1);assert.equal(JSON.parse(localStorage.getItem(key)).refresh_token,'fake-renewed-refresh');});
test('offline reopening preserves household sign-in and can retry later',async()=>{setup();localStorage.setItem(key,JSON.stringify(saved(Date.now()-1000)));globalThis.fetch=async()=>{throw TypeError('Offline');};const auth=await module();assert.equal((await auth.restore()).user.id,'fake-household');assert.ok(localStorage.getItem(key));globalThis.fetch=async()=>response(next());await auth.refresh();assert.equal(auth.getSession().access_token,'fake-renewed-access');});
test('temporary server failures do not sign out the household',async()=>{setup();localStorage.setItem(key,JSON.stringify(saved(Date.now()-1000)));globalThis.fetch=async()=>response({message:'Temporarily unavailable'},503);const auth=await module();assert.equal((await auth.restore()).user.id,'fake-household');assert.ok(localStorage.getItem(key));});
test('rejected refresh credentials require a new sign-in',async()=>{setup();localStorage.setItem(key,JSON.stringify(saved(Date.now()-1000)));globalThis.fetch=async()=>response({message:'Invalid refresh token'},400);const auth=await module();assert.equal(await auth.restore(),null);assert.equal(localStorage.getItem(key),null);});
test('sign-out cannot be undone by a refresh already in flight',async()=>{setup();localStorage.setItem(key,JSON.stringify(saved(Date.now()-1000)));let complete,started;const ready=new Promise(resolve=>{started=resolve;});globalThis.fetch=async()=>{started();return new Promise(resolve=>{complete=()=>resolve(response(next()));});};const auth=await module();const restoring=auth.restore();await ready;auth.signOut();complete();assert.equal(await restoring,null);assert.equal(localStorage.getItem(key),null);assert.equal(sessionStorage.getItem(key),null);});
test('two app windows serialize rotating refresh tokens through a shared lock',async()=>{setup();let queue=Promise.resolve();navigator.locks={request:(_name,work)=>{const result=queue.then(work);queue=result.catch(()=>{});return result;}};localStorage.setItem(key,JSON.stringify(saved(Date.now()-1000)));let refreshes=0;globalThis.fetch=async()=>{refreshes++;return response(next());};const first=await module(),second=await module();await Promise.all([first.restore(),second.restore()]);assert.equal(refreshes,1);assert.equal(first.getSession().access_token,second.getSession().access_token);});
test('blocked persistent storage reports that sign-in cannot be remembered',async()=>{setup();localStorage.setItem=()=>{throw Error('Quota');};globalThis.fetch=async()=>response(saved());const auth=await module();await assert.rejects(auth.signIn('fake@example.com','fake-password'),/could not remember/);assert.equal(auth.getSession(),null);});
