import {account,transaction,collect} from '../supabase/functions/coinplan-bank/logic.ts';
function equal(a:unknown,b:unknown){if(JSON.stringify(a)!==JSON.stringify(b))throw Error(JSON.stringify(a)+' != '+JSON.stringify(b));}
Deno.test('bank outflows and income have correct signs',()=>{equal(transaction({transaction_id:'x',account_id:'a',amount:12.50,iso_currency_code:'USD',personal_finance_category:{primary:'FOOD_AND_DRINK',detailed:'FOOD_AND_DRINK_GROCERIES'}})?.amount,1250);equal(transaction({amount:-50,iso_currency_code:'USD',personal_finance_category:{primary:'INCOME'}})?.amount,5000);});
Deno.test('credit card payments are transfers; refunds reduce spending',()=>{equal(transaction({amount:50,iso_currency_code:'USD',personal_finance_category:{primary:'LOAN_PAYMENTS',detailed:'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT'}})?.type,'transfer');equal(transaction({amount:-10,iso_currency_code:'USD',personal_finance_category:{primary:'GENERAL_MERCHANDISE'}})?.amount,-1000);});
Deno.test('foreign currencies are excluded instead of silently counted as dollars',()=>{equal(transaction({iso_currency_code:'EUR'}),null);equal(account({balances:{iso_currency_code:'EUR'}}),null);});
Deno.test('credit account balances are liabilities',()=>{equal(account({account_id:'a',name:'Card',type:'credit',balances:{iso_currency_code:'USD',current:250}})?.kind,'liability');});
Deno.test('sync stages all pages before exposing a next cursor',async()=>{const called:string[]=[];const r=await collect('',async cursor=>{called.push(cursor);return cursor===''?{added:[{id:'first'}],modified:[],removed:[],next_cursor:'a',has_more:true}:{added:[],modified:[{id:'second'}],removed:[{transaction_id:'old'}],next_cursor:'b',has_more:false};});equal(called,['','a']);equal(r.next,'b');equal(r.added.length,2);equal(r.removed,['plaid-old']);});
Deno.test('pagination mutation retries from the original cursor and drops partial pages',async()=>{let attempt=0;const r=await collect('original',async cursor=>{if(cursor==='original'){attempt++;return {added:[{id:attempt}],modified:[],removed:[],next_cursor:'next',has_more:true};}if(attempt===1)throw Object.assign(Error('changed'),{code:'TRANSACTIONS_SYNC_MUTATION_DURING_PAGINATION'});return {added:[],modified:[],removed:[],next_cursor:'done',has_more:false};});equal(r.added,[{id:2}]);equal(r.next,'done');});
Deno.test('failed sync does not yield partial records',async()=>{let rejected=false;try{await collect('',async()=>{throw Error('Bank unavailable');});}catch{rejected=true;}equal(rejected,true);});
