import test from 'node:test';import assert from 'node:assert/strict';import * as C from '../js/core.js';import 'fake-indexeddb/auto';import * as S from '../js/store.js';
const tx=(id,amount,type='expense',extra={})=>({id,amount,type,category:type==='income'?'income':'other',date:'2026-10-04',merchant:'Test',owner:'Shared',...extra});
test('money uses cents and rejects rounding ambiguity',()=>{assert.equal(C.cents('1,234.56'),123456);assert.equal(C.cents('-0.01'),-1);for(const v of ['1.001','Infinity','NaN','','1e3'])assert.throws(()=>C.cents(v));});
test('actual spending excludes scheduled bills, pending transactions, hidden entries and transfers',()=>{const s=C.emptyState();s.transactions=[tx('1',10000),tx('2',-2000),tx('3',30000,'transfer'),tx('4',50000,'income'),tx('5',4000,'expense',{pending:true}),tx('6',4000,'expense',{hidden:true})];s.bills=[{amount:10000}];assert.deepEqual({...C.monthSummary(s,'2026-10'),transactions:[],byCategory:{}},{income:50000,spent:8000,net:42000,transactions:[],byCategory:{}});});
test('ownership filter isolates personal spending',()=>{const s=C.emptyState();s.transactions=[tx('1',100,'expense',{owner:'Brody'}),tx('2',200,'expense',{owner:'Mackenzie'})];assert.equal(C.monthSummary(s,'2026-10','Brody').spent,100);});
test('monthly bill clamps short months and retains its original day',()=>{const b={anchor:'2026-01-31',frequency:'monthly'};assert.deepEqual(C.occurrences(b,'2026-02'),['2026-02-28']);assert.deepEqual(C.occurrences(b,'2026-03'),['2026-03-31']);assert.deepEqual(C.occurrences(b,'2025-12'),[]);});
test('biweekly schedule crosses month boundaries without resetting',()=>{const b={anchor:'2026-01-05',frequency:'biweekly'};assert.deepEqual(C.occurrences(b,'2026-02'),['2026-02-02','2026-02-16']);assert.deepEqual(C.occurrences(b,'2026-03'),['2026-03-02','2026-03-16','2026-03-30']);});
test('budget carries forward without future edits changing historical months',()=>{const s=C.emptyState();s.budgets={'2026-09':{income:100},'2026-11':{income:300}};assert.equal(C.budgetFor(s,'2026-10').income,100);assert.equal(C.budgetFor(s,'2026-11').income,300);assert.deepEqual(C.budgetFor(s,'2026-08'),{});});
test('net worth subtracts liabilities and excludes archived accounts',()=>{const s=C.emptyState();s.accounts=[{kind:'asset',balance:500},{kind:'liability',balance:200},{kind:'asset',balance:900,archived:true}];assert.equal(C.netWorth(s).total,300);});
test('CSV parses multiline cells, escaped quotes, and BOM',()=>{const p=C.parseCSV('\ufeffDate,Description,Amount\r\n10/04/2026,"Coffee, \"\"great\"\"\nplace",-12.50\r\n');assert.equal(p.rows[0][1],'Coffee, "great"\nplace');assert.throws(()=>C.parseCSV('a,b\n"oops,2'));});
test('CSV preserves two equal purchases and skips a repeated file',()=>{const parsed=C.parseCSV('Date,Merchant,Amount\n10/04/2026,Coffee,-5.00\n10/04/2026,Coffee,-5.00');const records=C.mapCSV(parsed,{date:0,merchant:1,amount:2},'a','Shared');let result=C.mergeImports(C.emptyState(),records);assert.equal(result.added,2);result=C.mergeImports(result.state,C.mapCSV(parsed,{date:0,merchant:1,amount:2},'a','Shared'));assert.equal(result.added,0);assert.equal(result.duplicates,2);});
test('CSV import rejects invalid dates and reports row numbers',()=>{assert.throws(()=>C.mapCSV(C.parseCSV('Date,Merchant,Amount\n02/30/2026,Coffee,-5'),{date:0,merchant:1,amount:2},'a','Shared'),/Row 2/);assert.equal(C.validDate('2024-02-29'),true);assert.equal(C.validDate('2026-02-29'),false);});
test('merchant rules assign transfers without counting them as spending',()=>{const r=C.applyRules(tx('1',500,'expense',{merchant:'Capital One Payment'}),[{match:'capital one',category:'transfer'}]);assert.equal(r.type,'transfer');});
test('posted bank replacement preserves edits from its pending transaction',()=>{const s=C.emptyState();s.accounts=[{id:'a',name:'Checking',kind:'asset',balance:0,owner:'Shared'}];s.transactions=[tx('pending',1500,'expense',{source:'plaid',accountId:'a',customCategory:'dining',note:'Date night',owner:'Brody'})];const result=C.mergeBank(s,{accounts:s.accounts,transactions:[tx('posted',1800,'expense',{source:'plaid',accountId:'a',pendingId:'pending'})]});assert.equal(result.transactions.length,1);assert.equal(result.transactions[0].category,'dining');assert.equal(result.transactions[0].note,'Date night');assert.equal(result.transactions[0].owner,'Brody');});
test('backup validation rejects malformed data and duplicate IDs',()=>{const s=C.emptyState();s.transactions=[tx('a',100),tx('a',200)];assert.throws(()=>C.validate(s));s.transactions=[tx('a',100,{})];assert.throws(()=>C.validate(s));});
test('IndexedDB persistence survives reading and rejects concurrent stale writes',async()=>{const s=C.emptyState(),a=await S.write('test',s,0);assert.equal((await S.read('test')).revision,1);await assert.rejects(S.write('test',s,0),/Another tab/);assert.equal((await S.read('test')).revision,1);});

test('bank refresh removes disconnected balances while preserving manual records and their account history',()=>{const s=C.emptyState();s.accounts=[{id:'manual',name:'Cash',kind:'asset',balance:200,owner:'Shared',source:'manual'},{id:'removed',name:'Old bank',kind:'asset',balance:900,owner:'Shared',source:'plaid'},{id:'history',name:'Old bank with notes',kind:'asset',balance:500,owner:'Brody',source:'plaid'},{id:'active',name:'Current bank',kind:'asset',balance:100,owner:'Mackenzie',source:'plaid'}];s.transactions=[tx('manual-tx',10,'expense',{source:'manual',accountId:'history'}),tx('bank-tx',20,'expense',{source:'plaid',accountId:'removed'})];const result=C.mergeBank(s,{accounts:[{...s.accounts[3],balance:300}],transactions:[]});assert.deepEqual(result.accounts.map(a=>a.id),['manual','history','active']);assert.equal(result.accounts.find(a=>a.id==='history').archived,true);assert.equal(result.accounts.find(a=>a.id==='active').owner,'Mackenzie');assert.equal(C.netWorth(result).total,500);assert.deepEqual(result.transactions.map(t=>t.id),['manual-tx']);});
