import {collect,transaction,account} from './logic.ts';
const env=(name:string)=>{const v=Deno.env.get(name);if(!v)throw Error('Missing server configuration: '+name);return v;};
const SUPA=env('SUPABASE_URL'),SERVICE=env('SUPABASE_SERVICE_ROLE_KEY');
const ORIGINS=(Deno.env.get('COINPLAN_ORIGINS')||'https://therealcrispy.github.io').split(',');
const ENV=Deno.env.get('PLAID_ENV')||'sandbox';
const PLAID=ENV==='production'?'https://production.plaid.com':'https://sandbox.plaid.com';
async function db(path:string,method='GET',body?:unknown){const r=await fetch(SUPA+'/rest/v1/'+path,{method,headers:{apikey:SERVICE,Authorization:'Bearer '+SERVICE,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Private storage request failed.');return r.status===204?null:await r.json();}
async function plaid(path:string,body:Record<string,unknown>){const r=await fetch(PLAID+path,{method:'POST',headers:{'Content-Type':'application/json','Plaid-Version':'2020-09-14'},body:JSON.stringify({client_id:env('PLAID_CLIENT_ID'),secret:env('PLAID_SECRET'),...body}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok){const error=Error(d.display_message||'Bank connection needs attention.');Object.assign(error,{code:d.error_code});throw error;}return d;}
async function cryptoKey(){const bytes=Uint8Array.from(atob(env('COINPLAN_TOKEN_KEY')),c=>c.charCodeAt(0));if(bytes.length!==32)throw Error('Invalid server encryption key.');return crypto.subtle.importKey('raw',bytes,{name:'AES-GCM'},false,['encrypt','decrypt']);}
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
async function seal(token:string){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(),new TextEncoder().encode(token)));return b64(iv)+'.'+b64(bytes);}
async function unseal(token:string){const [iv,data]=token.split('.').map(s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},await cryptoKey(),data));}
async function syncItem(item:Record<string,any>){const lease=crypto.randomUUID();const locked=await db('rpc/coinplan_bank_lease','POST',{p_item:item.id,p_owner:item.owner,p_lease:lease});if(!locked)return false;try{const token=await unseal(locked.token);const pages=await collect(locked.cursor,cursor=>plaid('/transactions/sync',{access_token:token,cursor,count:500}));const data=await plaid('/accounts/get',{access_token:token});await db('rpc/coinplan_bank_commit','POST',{p_item:item.id,p_owner:item.owner,p_lease:lease,p_cursor:pages.next,p_accounts:data.accounts.map(account).filter(Boolean),p_transactions:pages.added.map(transaction).filter(Boolean),p_removed:pages.removed});return true;}catch(e){await db('coinplan_bank_items?id=eq.'+encodeURIComponent(item.id)+'&owner=eq.'+item.owner+'&lease=eq.'+lease,'PATCH',{lease:null,lease_until:null});throw e;}}
export async function handle(req:Request){const origin=req.headers.get('Origin');const headers={'Content-Type':'application/json',...(origin&&ORIGINS.includes(origin)?{'Access-Control-Allow-Origin':origin,Vary:'Origin'}:{}),'Access-Control-Allow-Headers':'authorization,apikey,content-type,x-coinplan-cron','Access-Control-Allow-Methods':'POST,OPTIONS','Cache-Control':'no-store'};const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});if(origin&&!ORIGINS.includes(origin))return reply({error:'Origin is not allowed.'},403);if(req.method==='OPTIONS')return new Response(null,{headers});if(req.method!=='POST')return reply({error:'POST required.'},405);try{if(Number(req.headers.get('content-length')||0)>10000)return reply({error:'Request too large.'},413);const text=await req.text();if(text.length>10000)return reply({error:'Request too large.'},413);const body=JSON.parse(text);const cron=req.headers.get('x-coinplan-cron');if(body.action==='scheduled'){if(!cron||cron!==Deno.env.get('COINPLAN_CRON_SECRET'))return reply({error:'Unauthorized'},401);const items=await db('coinplan_bank_items?select=id,owner&limit=100');let synced=0,failed=0;for(const item of items){try{if(await syncItem(item))synced++;}catch{failed++;}}return reply({synced,failed});}
 const authorization=req.headers.get('Authorization');if(!authorization?.startsWith('Bearer '))return reply({error:'Sign in required.'},401);const auth=await fetch(SUPA+'/auth/v1/user',{headers:{apikey:env('SUPABASE_ANON_KEY'),Authorization:authorization},signal:AbortSignal.timeout(10000)});if(!auth.ok)return reply({error:'Sign in again.'},401);const user=await auth.json(),owner=user.id;if(!owner)return reply({error:'Invalid user.'},401);if(!env('COINPLAN_ALLOWED_USER_IDS').split(',').includes(owner))return reply({error:'Bank access is limited to this household. Ask the project owner to enable your account.'},403);
 if(body.action==='connections'){const items=await db('coinplan_bank_items?select=id,institution&owner=eq.'+owner);return reply({items});}
 if(body.action==='link'&&body.item_id){const items=await db('coinplan_bank_items?select=id,token&owner=eq.'+owner+'&id=eq.'+encodeURIComponent(body.item_id));if(!items.length)return reply({error:'Connection not found.'},404);const data=await plaid('/link/token/create',{user:{client_user_id:owner},client_name:'CoinPlan',access_token:await unseal(items[0].token),country_codes:['US'],language:'en',redirect_uri:env('COINPLAN_REDIRECT_URI')});return reply({link_token:data.link_token,environment:ENV});}
 if(body.action==='link'){const items=await db('coinplan_bank_items?select=id&owner=eq.'+owner);if(items.length>=4)return reply({error:'Connection limit reached. Contact the project owner before adding more.'},409);const data=await plaid('/link/token/create',{user:{client_user_id:owner},client_name:'CoinPlan',products:['transactions'],country_codes:['US'],language:'en',redirect_uri:env('COINPLAN_REDIRECT_URI'),transactions:{days_requested:365}});return reply({link_token:data.link_token,environment:ENV});}
 if(body.action==='exchange'){if(typeof body.public_token!=='string'||body.public_token.length>300)return reply({error:'Invalid connection token.'},400);const d=await plaid('/item/public_token/exchange',{public_token:body.public_token});const existing=await db('coinplan_bank_items?id=eq.'+encodeURIComponent(d.item_id)+'&select=id,owner');if(existing.length){if(existing[0].owner!==owner)return reply({error:'Connection belongs to another household.'},403);return reply({connected:true});}try{await db('coinplan_bank_items','POST',{id:d.item_id,owner,token:await seal(d.access_token),institution:String(body.institution||'Bank').slice(0,120)});}catch(e){await plaid('/item/remove',{access_token:d.access_token});throw e;}return reply({connected:true});}
 if(body.action==='sync'){const items=await db('coinplan_bank_items?select=id,owner&owner=eq.'+owner);let warning='';for(const item of items){try{if(!await syncItem(item))warning='A bank refresh is already running. Try again shortly.';}catch(e){warning=(e as Error).message;}}const accounts=await db('coinplan_bank_accounts?select=payload&owner=eq.'+owner),transactions=[];for(let offset=0;offset<100000;offset+=1000){const rows=await db('coinplan_bank_transactions?select=payload&owner=eq.'+owner+'&order=id&limit=1000&offset='+offset);transactions.push(...rows.map((r:Record<string,any>)=>r.payload));if(rows.length<1000)break;}return reply({accounts:accounts.map((r:Record<string,any>)=>r.payload),transactions,warning});}
 return reply({error:'Unknown action.'},400);
 }catch(e){return reply({error:(e as Error).message},400);}}

